import telebot

# keyboards creating
keyboard_for_page_one = telebot.types.ReplyKeyboardMarkup(True)
keyboard_for_page_one.row('Перемены в жизни', 'Очищение/Чистка')
keyboard_for_page_one.row('Эмоциональная стабилизация', 'Любовь/Отношения')
keyboard_for_page_one.row('Финансы')
keyboard_for_page_one.row('Связаться с мастером ')
keyboard_for_page_two = telebot.types.ReplyKeyboardMarkup(True)
keyboard_for_page_two.row('Перезагрузка реальности', 'Исполнение желаний')
keyboard_for_page_two.row('Свеча-прорыв')
keyboard_for_page_two.row('Назад', 'Связаться с мастером')
keyboard_for_page_three = telebot.types.ReplyKeyboardMarkup(True)
keyboard_for_page_three.row('Полынный сет', 'Универсальная чистка')
keyboard_for_page_three.row('В разработке')
keyboard_for_page_three.row('Назад', 'Связаться с мастером')
keyboard_for_page_four = telebot.types.ReplyKeyboardMarkup(True)
keyboard_for_page_four.row('Успокоение', 'Молитва')
keyboard_for_page_four.row('От тяжких дум')
keyboard_for_page_four.row('Назад', 'Связаться с мастером')
keyboard_for_page_five = telebot.types.ReplyKeyboardMarkup(True)
keyboard_for_page_five.row('Сладкая парочка', 'Привлечение любви')
keyboard_for_page_five.row('Гармонизация отношений')
keyboard_for_page_five.row('Назад', 'Связаться с мастером')
keyboard_for_page_six = telebot.types.ReplyKeyboardMarkup(True)
keyboard_for_page_six.row('Денежная', 'Чистка фин.потока')
keyboard_for_page_six.row('Финансовый успех')
keyboard_for_page_six.row('Назад', 'Связаться с мастером')


